--TABLA CUSTOMERS
CREATE TABLE [dbo].[TBL_CUSTOMERS]
(
	[ID] NVARCHAR(15) NOT NULL PRIMARY KEY, 
    [NAME] NVARCHAR(50) NOT NULL, 
    [LAST_NAME] NVARCHAR(50) NOT NULL, 
    [AGE] NUMERIC NOT NULL
)

--INSERT EN  CUSTOMERS
CREATE PROCEDURE [dbo].[CRE_CUSTOMER_PR]
	@P_ID nvarchar(25),
	@P_NAME nvarchar(25),
	@P_LAST_NAME nvarchar(25),
	@P_AGE int
AS
	INSERT INTO [dbo].[TBL_CUSTOMERS] VALUES(@P_ID,@P_NAME,@P_LAST_NAME,@P_AGE);
GO;
